name: Build JDK
description: Install the dependencies and build the JDK
inputs:
  architecture:
    description: The target architecture.
    required: true
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    - run: pipx install poetry==1.7.0
      shell: bash

    - id: setup_python
      uses: actions/setup-python@v4
      with:
        cache: "poetry"
        python-version: ${{ inputs.python-version }}

    - run: poetry install
      shell: bash

    - run: poetry run python scripts/set_environment.py
      shell: bash

    - uses: actions/setup-java@v3
      with:
        architecture: ${{ inputs.architecture }}
        distribution: temurin
        java-version: ${{ env.JDK4PY_JAVA_VERSION }}

    - run: poetry run python scripts/build_jdk.py
      shell: bash
